feat: delete material
10clouds/aiconsole pull request #10
Opened 2023-10-17 10:45 UTC by jakubbilko

2023-10-17 11:01 UTC, piotr10clouds commented on aiconsole/materials/materials.py
> +                os.remove(material_file_path)
if material_file_path is pathlib.Path:
```suggestion
                material_file_path.unlink()
```
And we should not to use "os".

2023-10-17 13:57 UTC, cielecki requested changes

2023-10-17 13:57 UTC, cielecki commented on aiconsole/materials/core/today.toml
This should not be deleted right?

2023-10-17 13:57 UTC, cielecki commented on aiconsole/materials/materials.py
> +            del self._materials[material_id]
This should not be necessary, as reload will happen after deleting the file

2023-10-18 09:54 UTC, cielecki approved these changes

2023-10-18 09:54 UTC, merged