python virtualenv per project and correct path for embedded interpreter
10clouds/aiconsole pull request #105
Opened 2023-11-16 15:35 UTC by dydek

2023-11-16 15:37 UTC, dydek commented on backend/aiconsole/core/code_running/code_interpreters/languages/python.py
> +#from aiconsole.dev.credentials import MissingCredentialException
this is something I'm not so sure about - if we want to still use it we'd need to install aiconsole package in every venv - which is possible but I wanted to have your opinion before that

2023-11-16 15:38 UTC, dydek commented on backend/aiconsole/core/code_running/code_interpreters/subprocess_code_interpreter.py
> +                                        env=self._prepare_env(),
the main part to modify the env for the execution

2023-11-16 15:41 UTC, dydek commented on backend/aiconsole/core/code_running/code_interpreters/languages/python.py
> +        self.start_cmd = "python -i -q -u"
probably ( I guess ) for win32 it should be the name with `exe` -  a small fix is required probably

2023-11-17 01:11 UTC, cielecki requested changes

2023-11-17 01:11 UTC, cielecki commented on backend/aiconsole/core/code_running/code_interpreters/languages/python.py
> +#from aiconsole.dev.credentials import MissingCredentialException
yes we need to do that - some of the materials need to have access to the packages.

There is a space to maybe seperate a package for materials development that will be smaller but I'm not sure if it's worth the effort.

2023-11-23 09:02 UTC, merged