Fix user avatar for older chats
10clouds/aiconsole pull request #490
Opened 2024-01-02 18:50 UTC by udislau

https://github.com/10clouds/aiconsole/issues/489

* feat(profile.py): add default avatar URL and optional email parameter
* refactor(UserAvatar.tsx, UserInfo.tsx, chatTypes.ts): allow null values for email and username

2024-01-02 20:59 UTC, cielecki requested changes

2024-01-02 20:59 UTC, cielecki commented on frontend/src/types/editables/chatTypes.ts
> +  username: z.string().nullable(),
In other places we use optional (undefined) and not nullable (null)

2024-01-02 20:59 UTC, cielecki commented on backend/aiconsole/api/endpoints/profile.py
> +DEFAULT_AVATAR_URL = "https://gravatar.com/avatar/?d=mp"
We already have a default avatar in our fastapi server, we used it already before. We should use that one.

2024-01-03 09:56 UTC, pbaranski9411 requested changes

2024-01-03 09:56 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +        return UserProfile(username=f"user", avatar_url=DEFAULT_AVATAR_URL)
First of all, f-string is not needed here. Second of all, why username is hardcoded here? 🤔 maybe I'm missing something, let me know! :)

2024-01-03 09:56 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +        return UserProfile(username=f"{email}", avatar_url=DEFAULT_AVATAR_URL)
```suggestion
        return UserProfile(username=email, avatar_url=DEFAULT_AVATAR_URL)
```

2024-01-03 18:56 UTC, udislau commented
Updates in https://github.com/10clouds/aiconsole/pull/490/commits/ffaa361f6e54260595559931eb4bf0f17fcd10d6

2024-01-04 12:23 UTC, pbaranski9411 requested changes

2024-01-04 12:23 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +    username: str = "user"
1. I think that kind of defaults should be set in domain / business logic services, not in endpoints / api layer (here we can set None, then in service we can set proper const by default)
2. We can create const somewhere instead of hardcoded string

2024-01-04 12:23 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +    gravatar: bool = False
the same as above, those kind of consts could be set in service/domain level

2024-01-04 12:23 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +    return choices[choice_index]
this is something which should be in some kind of service, not in api layer

2024-01-04 12:23 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +        return UserProfile(username=email, avatar_url=f"/profile_image?img_filename={img_filename}")
the same as above :) 
Logic in domain / business services | routing/api requests and responses here only

2024-01-04 20:29 UTC, pbaranski9411 requested changes

2024-01-04 20:29 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +            return profile
```suggestion
class UserProfileService:
    def __init__(self, gravatar_profile_service: GravatarProfileService) -> None:
        self._gravatar_profile_service = gravatar_profile_service
        
    @staticmethod
    def get_profile(email: str | None = None) -> UserProfile:
        if email is not None and (profile := self._gravatar_profile_service.get_gravatar_profile(email)):
            return profile
```

2024-01-04 20:29 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +            return profile
It could be injected as dependency (because it's dependency at all)

2024-01-04 20:29 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +        )
this included two "if email" statements. It could be done before that to keep one if statement instead

2024-01-04 20:29 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +    def get_profile_image_path(img_filename: str):
return type.

btw @cielecki maybe it's good time to introduce mypy here? (and check it on CI/CD too?)

2024-01-04 20:29 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +            avatar_url=UserProfileService._get_default_avatar(email=email)
if it's uses private methods, obviously those methods are not static.

UserProfileService should have public and private methods (not static) and it should be singleton (one instance)

2024-01-05 11:57 UTC, pbaranski9411 requested changes

2024-01-05 11:57 UTC, pbaranski9411 commented on backend/aiconsole/base/singleton.py
> +        return cls._instance
Why not just lru_cache with method?

This is not needed, you can create simple method:

```
@lru_cache
def gravatar_client() -> GravatarClient:
    return GravatarClient()
```

and pass it through Depends(gravatar_client) to proper endpoint handler
```

2024-01-05 11:57 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +class UserProfileService(Singleton):
the same as above with Singleton thing

2024-01-05 12:40 UTC, udislau commented on backend/aiconsole/base/singleton.py
> +        return cls._instance
I believe that calling UserProfileService is more strait-forward way, than having separate function for retrieving, which can lead to many misunderstandings of how to use in a proper way the service. + No error will be shown if improperly used. Additionally, with lru the new instance of a service can still be created.

2024-01-05 18:09 UTC, pbaranski9411 approved these changes

2024-01-05 18:09 UTC, pbaranski9411 commented on backend/.pre-commit-config.yaml
> +# See https://pre-commit.com for more information
it's not related with the task, but it's ok. @cielecki FYI

2024-01-05 18:09 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +def profile(email: Optional[str] = None) -> UserProfile:
```suggestion
def profile(email: Optional[str] = None, user_profile_service: UserProfileService = Depends(user_profile_service)) -> UserProfile:
```

2024-01-06 08:37 UTC, merged