Don't allow to create user agent
10clouds/aiconsole pull request #516
Opened 2024-01-04 12:19 UTC by pbaranski9411

2024-01-04 15:25 UTC, udislau requested changes
Check comments

2024-01-04 15:25 UTC, udislau commented on backend/aiconsole/api/endpoints/services.py
> +    def _validate_invalid_agent_ids(self, agent_id: str) -> None:
Lets name it _validate_agent_id

2024-01-04 15:25 UTC, udislau commented on backend/aiconsole/api/endpoints/services.py
> +    def _validate_invalid_agent_ids(self, agent_id: str) -> None:
+ _validate_existance in _Assets has misspell _validate_existence

2024-01-04 15:25 UTC, udislau commented on backend/aiconsole/api/endpoints/services.py
> +            raise InvalidAgentNameError()
We can write some text as param to explain the error, so that later we can reuse it in the response

2024-01-04 15:25 UTC, udislau commented on backend/aiconsole/api/endpoints/agents/agent.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid agent name. Try to use another one"
We can get detail directly form the error, check comment for services.py

2024-01-04 15:35 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/services.py
> +            raise InvalidAgentNameError()
I'm not sure if it's good idea here. 
Domain/business service role is only for validate things. Human readable message should be generated by API/endpoints layer which is responsible for that. For example if 3 endpoints will use the same service method which is possible, they can create different messages for the user

2024-01-04 15:35 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/agents/agent.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid agent name. Try to use another one"
As above

2024-01-04 15:35 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/services.py
> +    def _validate_invalid_agent_ids(self, agent_id: str) -> None:
Good idea, will do 👍

2024-01-04 17:44 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/services.py
> +            raise InvalidAgentNameError()
In this case I think it doesn't matter at all :) The main thing is that service layer is validating and raising error and api layer is doing rest things.
I can add error message here if you want, but I think it's redundant

2024-01-04 19:11 UTC, udislau commented on backend/aiconsole/api/endpoints/services.py
> +            raise InvalidAgentNameError()
Ok, then waiting for changes with names

2024-01-05 05:16 UTC, cielecki commented
When I look at the code, it seems to have been implemented already in load_asset_from_fs and save_asset_to_fs

2024-01-05 05:18 UTC, cielecki requested changes

2024-01-05 05:18 UTC, cielecki commented on backend/aiconsole/api/endpoints/services.py
> +    _INVALID_AGENT_IDS = {"user"}
When I look at the code, it seems to have been implemented already in load_asset_from_fs and save_asset_to_fs, has this implementation taken that into account / refactored that?

2024-01-08 13:10 UTC, cielecki requested changes

2024-01-08 13:10 UTC, cielecki commented on backend/aiconsole/core/assets/fs/save_asset_to_fs.py
> +class CannotSaveAgentWithIdUserError(Exception):
Have one exception for this case: both for save and load and raise and handle it appropriately.

2024-01-12 14:49 UTC, cielecki approved these changes

2024-01-14 09:07 UTC, merged