Feat/users settings
10clouds/aiconsole pull request #521
Opened 2024-01-04 16:41 UTC by udislau

2024-01-07 18:34 UTC, udislau commented
Added POST /profile_image with `avatar` param for file upload

2024-01-08 11:36 UTC, pbaranski9411 requested changes

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +        file_object.write(avatar.file.read())
This could be moved to the service

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/profile.py
> +    return {"info": "Avatar uploaded successfully", "filename": avatar.filename}
info is really needed here? I think 201 response is good enough to wrap status_code to proper message on frontend.

I think there is no need to pass such things as response for api call

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/project_settings.py
> +async def patch(patch_data: PartialSettingsData, settings: Settings = Depends(settings)):
```suggestion
async def partially_update_project_settings(patch_data: PartialSettingsData, settings: Settings = Depends(settings)):
```

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/project_settings.py
> +        _log.debug(f"PATCHingh settings with {patch_data}")
no need for that kind of logs

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/api/endpoints/project_settings.py
> +async def get(settings: Settings = Depends(settings)):
```suggestion
async def get_project_settings(settings: Settings = Depends(settings)):
```

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/consts.py
> +    return Path(user_config_dir(APPLICATION_NAME))
why method, not just const? 🤔

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +            assets[0] for assets in self._assets.values() if self.get_status(self.asset_type, assets[0].id) in [status]
```suggestion
            assets[0] for assets in self._assets.values() if self.get_status(self.asset_type, assets[0].id) == status
```

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +        s = settings().settings_data
settings could be injected in `__init__` method and use here (self._settings)

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +        s = settings().settings_data
`s` is not meaningful, you can use other name which will be self explanated

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +            raise ValueError(f"Unknown asset type {asset_type}")
When I see such if/else statements which is type based, I think it could be splitted to two different methods and used properly when needed:

```
def get_material_status()
def get_agent_status()
...
```

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +            raise ValueError(f"Unknown asset type {asset_type}")
the same as above when it comes to the types selection

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/assets/assets.py
> +            raise ValueError(f"Unknown asset type {asset_type}")
the same as above when it comes to the types selection

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/gpt/check_key.py
> +def check_key(key: str) -> bool:
👍

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/project/paths.py
> +    _log.debug(f"project_directory -> {project_directory}")
no needed

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/project/project.py
> +    await settings().reload()  # type: ignore # TODO: do not show setting message "reloaded"
something should be done with this TODO? (task or fix here? )

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/project/project.py
> +    await settings().reload()  # type: ignore # TODO: do not show setting message "reloaded"
the same as above

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/settings/base/observer.py
> +        ...
(comment for every similar places too)

I think for such things it would be better to use `pass` instead

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/users/models.py
> +    def __init__(self, **data):
I'm not sure if passing such **data is good idea (mypy will reject it). Please use proper types here

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/users/models.py
> +        if "email" in data and data["email"] is not None:
```suggestion
        if data.get("email") is not None:
```

2024-01-08 11:36 UTC, pbaranski9411 commented on backend/aiconsole/core/users/models.py
> +            data["username"] = str(data["email"]).split("@")[0]
I think there is EmailField in fastapi which will do the job for you.

If not, there will be need for regexp validation too

2024-01-08 11:41 UTC, udislau commented on backend/aiconsole/consts.py
> +    return Path(user_config_dir(APPLICATION_NAME))
During bundle_python in Electron, this file is needed.

It's so that you can bundle python without a need of installing 3 party packages.

2024-01-08 18:18 UTC, udislau commented on backend/aiconsole/api/endpoints/profile.py
> +        file_object.write(avatar.file.read())
Done

2024-01-08 18:18 UTC, udislau commented on backend/aiconsole/api/endpoints/profile.py
> +    return {"info": "Avatar uploaded successfully", "filename": avatar.filename}
Done

2024-01-08 18:19 UTC, udislau commented on backend/aiconsole/api/endpoints/project_settings.py
> +async def patch(patch_data: PartialSettingsData, settings: Settings = Depends(settings)):
Done

2024-01-08 18:19 UTC, udislau commented on backend/aiconsole/api/endpoints/project_settings.py
> +        _log.debug(f"PATCHingh settings with {patch_data}")
Done

2024-01-08 18:20 UTC, udislau commented on backend/aiconsole/api/endpoints/project_settings.py
> +async def get(settings: Settings = Depends(settings)):
Done

2024-01-08 18:23 UTC, udislau commented on backend/aiconsole/core/gpt/check_key.py
> +def check_key(key: str) -> bool:
I don't know what you mean here

2024-01-08 18:25 UTC, udislau commented on backend/aiconsole/core/project/project.py
> +    await settings().reload()  # type: ignore # TODO: do not show setting message "reloaded"
Old one, removed it

2024-01-09 09:10 UTC, udislau commented on backend/aiconsole/core/assets/assets.py
> +        s = settings().settings_data
About changes in `assets.py`. I only moved the code from `project_setttings`. I want to refactor the `assets` after finishing work on `settings`. So I'll this comment for that.

2024-01-09 09:10 UTC, udislau commented on backend/aiconsole/core/assets/assets.py
> +            raise ValueError(f"Unknown asset type {asset_type}")
About changes in `assets.py`. I only moved the code from `project_setttings`. I want to refactor the `assets` after finishing work on `settings`. So I'll this comment for that.

2024-01-09 09:40 UTC, udislau commented on backend/aiconsole/core/users/models.py
> +            data["username"] = str(data["email"]).split("@")[0]
It is already done by Pydantic:

 `email: EmailStr | None = None`

2024-01-10 12:58 UTC, pbaranski9411 commented on backend/aiconsole/core/gpt/check_key.py
> +def check_key(key: str) -> bool:
That it's good that you found this thing and removed it :) It's kudos for you :)

2024-01-10 12:58 UTC, pbaranski9411 commented on backend/aiconsole/core/project/paths.py
> +    _log.debug(f"project_directory -> {project_directory}")
What about that?

2024-01-10 13:11 UTC, pbaranski9411 requested changes

2024-01-10 13:11 UTC, pbaranski9411 commented on backend/aiconsole/utils/BatchingWatchDogHandler.py
> +        _log.debug("❗️❗️❗️❗️File modified❗️❗️❗️❗️")
Hmmm, it's fine to have it like that, but I think it could be done differently.

Remember about types :) There will be mypy soon to check those types in all files

2024-01-10 13:11 UTC, pbaranski9411 commented on backend/aiconsole/core/users/user.py
> +            avatar_folder_path.mkdir(parents=False, exist_ok=True)
```suggestion
        avatar_folder_path.mkdir(parents=False, exist_ok=True)
```

Could you check if it will be enough? You types exist_ok, so I think this if statement is redundant

2024-01-10 13:11 UTC, pbaranski9411 commented on backend/aiconsole/core/users/models.py
> +    def __init__(self, **data: Any):
The best will be to have explicitly here what values and keys will be passed instaed of untyped data.

Mypy will raise error here too

2024-01-10 13:11 UTC, pbaranski9411 commented on backend/aiconsole/core/users/models.py
> +        if not data.get("username"):
What about empty string username? Is it ok to have one?

2024-01-10 13:11 UTC, pbaranski9411 commented on backend/aiconsole/core/settings/storage.py
> +        print(settings_data.model_dump(exclude_none=True, exclude={"to_global"}))
print to be removed

2024-01-10 13:11 UTC, pbaranski9411 commented
One more thing. Could you go through it and check if you have some errors in mypy? For example -> None return type? 🤔

2024-01-11 11:57 UTC, udislau commented on backend/aiconsole/core/settings/storage.py
> +        print(settings_data.model_dump(exclude_none=True, exclude={"to_global"}))
Done

2024-01-11 12:10 UTC, udislau commented on backend/aiconsole/core/users/user.py
> +            avatar_folder_path.mkdir(parents=False, exist_ok=True)
Checked info, They have different methods of verifying the existence, but `exist_ok` seems to be self sufficient.

2024-01-11 12:12 UTC, udislau commented on backend/aiconsole/utils/BatchingWatchDogHandler.py
> +        _log.debug("File modified!")
Removed

2024-01-11 12:12 UTC, udislau commented on backend/aiconsole/utils/BatchingWatchDogHandler.py
> +        _log.debug("❗️❗️❗️❗️File modified❗️❗️❗️❗️")
Removed

2024-01-11 13:34 UTC, udislau commented on backend/aiconsole/core/users/models.py
> +        if not data.get("username"):
Changed

2024-01-11 15:34 UTC, udislau commented
@cielecki Do you want to take a look at it one more time before merge?

2024-01-12 14:50 UTC, cielecki commented
> @cielecki Do you want to take a look at it one more time before merge?

No

2024-01-13 16:00 UTC, merged