#833 Fix/selected execution mode
10clouds/aiconsole pull request #863
Opened 2024-02-21 19:39 UTC by Zibi95

AgentForm reads actual execution mode and pass it to Select component

![Animation](https://github.com/10clouds/aiconsole/assets/78635631/c18c9f01-f20f-48a0-8edb-ef30f3183e41)

2024-02-22 07:41 UTC, udislau requested changes
1) Go to existing agent with custom execution mode, select normal or interpreter. You can’t save it now


https://github.com/10clouds/aiconsole/assets/30052145/51683ce5-71c2-437d-b081-708926c3ceee



2) Try to replicate the video, after `restore original` execution mode field is empty.

https://github.com/10clouds/aiconsole/assets/30052145/16444c34-1b45-4e2a-8b09-b4802384b3cf

2024-02-23 17:19 UTC, Zibi95 commented on frontend/src/components/editables/assets/AgentForm.tsx
> +
Do you mean that empty line? Ah, I did that reflexively. I've learned to separate imports from node_modules and local imports.

2024-03-06 14:41 UTC, nkvch commented
Solved conflicts in #906

2024-03-06 14:41 UTC, closed without merging

2024-03-06 14:41 UTC, nkvch commented
Solved conflicts in #906