feat: add draft message data to chat
10clouds/aiconsole pull request #867
Opened 2024-02-22 14:16 UTC by nkvch

2024-02-22 14:57 UTC, udislau requested changes
Draft during execution disappears

https://github.com/10clouds/aiconsole/assets/30052145/3445d9de-7f9f-4c79-981b-37318dde8e2f

2024-02-22 23:11 UTC, nkvch commented
I see. I've figured out the origin of the problem. Will fix or workaround it tomorrow morning

2024-02-23 07:54 UTC, udislau commented
> I see. I've figured out the origin of the problem. Will fix or workaround it tomorrow morning

Plz don't do any workarounds, you have time to implement it properly till 6pm 🙂

2024-02-23 16:19 UTC, nkvch commented
Okay, the issue fixed. Though I am not too sure about the purpose of chat locking mechanism, so I hope I didn't break anything :sweat_smile:. At least from what I see it works properly.
The other idea was to create a separate API service for draft messages, but I saw it as overkill

2024-02-23 16:21 UTC, nkvch commented on backend/aiconsole/core/chat/locking.py
> +    current_draft_message = await load_current_draft_message(chat_id)
@udislau is this ok?

2024-02-24 21:11 UTC, cielecki commented
draft_message should be part of chat_options

2024-02-26 13:29 UTC, closed without merging