Draft: custom params set for execution mode
10clouds/aiconsole pull request #909
Opened 2024-03-07 17:07 UTC by nkvch

2024-03-08 18:22 UTC, nkvch commented
Backend part is done. There are some minor frontend hazards that I will fix monday

2024-03-10 10:16 UTC, udislau requested changes

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/api/endpoints/execution_modes.py
> +    return ExecutionModeParams.model_json_schema()["properties"]
this is a core logic, not api

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/api/endpoints/execution_modes.py
> +        return None
User needs to see the err in the app

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/core/assets/agents/agent.py
> +    execution_mode: AgentExecutionMode = AgentExecutionMode()
Field(default_factory=...)

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/core/assets/agents/agent_execution_modes/__init__.py
No need for now to create subdir, increases complexity when it's not needed

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/core/chat/execution_modes/example_countdown.py
> +    from_: int = Field(default=10, alias="from")
What is "from_" and what  is alias "from" does?

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/core/chat/execution_modes/example_countdown.py
> +    to: int = Field(default=1)
No need in Field(default ...) unless it is a callable

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/core/chat/execution_modes/example_countdown.py
> +    **kwargs,
Don't use **kwargs in our code, is there a way to not use it here?

2024-03-10 10:16 UTC, udislau commented on backend/aiconsole/preinstalled/agents/assistant.toml
> +execution_mode = { module_path = "aiconsole.core.chat.execution_modes.normal:execution_mode" }
What is the purpose of {} for assignment?

2024-03-11 13:15 UTC, nkvch commented on backend/aiconsole/api/endpoints/execution_modes.py
> +    return ExecutionModeParams.model_json_schema()["properties"]
moved to core

2024-03-11 13:15 UTC, nkvch commented on backend/aiconsole/core/assets/agents/agent.py
> +    execution_mode: AgentExecutionMode = AgentExecutionMode()
done

2024-03-11 13:15 UTC, nkvch commented on backend/aiconsole/core/assets/agents/agent_execution_modes/__init__.py
ok

2024-03-11 13:16 UTC, nkvch commented on backend/aiconsole/core/chat/execution_modes/example_countdown.py
> +    from_: int = Field(default=10, alias="from")
that was generated by cursor, changed to "start"

2024-03-11 13:16 UTC, nkvch commented on backend/aiconsole/core/chat/execution_modes/example_countdown.py
> +    **kwargs,
replaced with params_values argument for this Protocol

2024-03-11 13:17 UTC, nkvch commented on backend/aiconsole/preinstalled/agents/assistant.toml
> +execution_mode = { module_path = "aiconsole.core.chat.execution_modes.normal:execution_mode" }
agent's execution_mode is not a string anymore but a structure (dict) with module_path and params_values

2024-03-12 07:10 UTC, udislau approved these changes

2024-03-12 07:11 UTC, merged